// First-party presentation only. Server authorization remains authoritative.
export const CONSUMER_PRESENTATION = `
(function () {
  if (document.getElementById('consumer-simple-style')) return;
  var uz=document.documentElement.lang==='uz', style=document.createElement('style');style.id='consumer-simple-style';
  style.textContent='body.ui-audit.page-nearby.directoryMode .intro,.page-nearby .catalogTabs,.page-nearby .viewLinks,.page-nearby .advisorDetails,.page-nearby #directorySummary,.page-nearby #catalogHint,.page-nearby .note{display:none!important} a[href^="/admin"],a[href^="/business"],a[href^="/owner"],a[href^="/staff"],a[href^="/review"]{display:none!important} .page-nearby .directoryPanel{margin-top:0!important;padding:16px!important;background:#0b2230!important;border-radius:18px!important} .page-nearby .catalogSearchWrap{padding:0!important;margin:12px 0!important;display:flex!important;gap:8px!important} .page-nearby .catalogSearchWrap .searchField{flex:1;min-width:0;font-size:0!important} .page-nearby .catalogSearch{font-size:16px!important;height:50px!important} .page-nearby .catalogSearchButton{width:auto!important;min-width:72px!important;font-size:14px!important;height:50px!important} .page-nearby .directorySelects{display:grid!important;grid-template-columns:1fr!important;margin-top:12px} .page-nearby .layout{margin-top:12px!important} .page-nearby .listHeader{padding:12px!important;flex-wrap:wrap} .consumerTitle{font-size:26px;line-height:1.2;margin:0 0 8px} .consumerHint{font-size:14px;line-height:1.4;color:#a5bdc7;margin:0 0 12px} .consumerPlace summary{min-height:44px;display:flex;align-items:center;cursor:pointer;color:#89e5c7;font-size:15px;font-weight:700} .consumerChips{display:flex;gap:8px;overflow:auto;padding:4px 0 10px} .consumerChips button{min-height:44px;flex:none;border:1px solid #31566a;border-radius:22px;background:#112f3e;color:#e0eee9;padding:8px 14px;font-size:14px} .consumerChips button[aria-pressed="true"]{background:#76e4c0;color:#08281e} .consumerMap{margin-top:12px!important;min-height:44px!important;font-size:14px!important}';document.head.append(style);
  if(!document.body.classList.contains('page-nearby'))return;
  var panel=document.getElementById('directoryPanel'),selects=panel.querySelector('.directorySelects'),region=document.getElementById('ratedRegion'),city=document.getElementById('ratedCity'),category=document.getElementById('ratedCategory');
  var title=document.createElement('h1');title.className='consumerTitle';title.dataset.appCopy='title';title.textContent=uz?'Nima izlayapsiz?':'Что вы ищете?';
  var hint=document.createElement('p');hint.className='consumerHint';hint.dataset.appCopy='hint';hint.textContent=uz?'Xizmat yoki tashkilot nomini yozing.':'Напишите услугу или название организации.';
  var place=document.createElement('details');place.className='consumerPlace';var summary=document.createElement('summary');place.append(summary,selects);panel.prepend(title,hint,place);
  var query=document.getElementById('catalogQuery');query.placeholder=uz?'Masalan: stomatologiya':'Например: стоматология';query.setAttribute('aria-label',uz?'Xizmat qidirish':'Поиск услуги');document.getElementById('catalogSearchButton').textContent=uz?'Topish':'Найти';
  var chips=document.createElement('div');chips.className='consumerChips';chips.setAttribute('aria-label',uz?'Xizmatlar':'Услуги');
  [['ALL','Все','Barchasi'],['FOOD','Еда','Taom'],['HEALTH','Здоровье','Salomatlik'],['RETAIL','Магазины','Do‘konlar'],['AUTO_SERVICE','Авто','Avto'],['BEAUTY','Красота','Go‘zallik']].forEach(function(item){var b=document.createElement('button');b.type='button';b.textContent=item[uz?2:1];b.dataset.category=item[0];b.addEventListener('click',function(){category.value=item[0];category.dispatchEvent(new Event('change',{bubbles:true}));});chips.append(b);});panel.querySelector('.catalogSearchWrap').after(chips);
  var locate=document.getElementById('locate');locate.classList.add('consumerMap');document.getElementById('listCard').after(locate);
  var key='relyqo.consumer.place.v1',restored=false,restoring=false;
  function sync(){
    if(!restored&&window.relyqoUzbekistan){restored=true;restoring=true;try{var saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&Array.from(region.options).some(function(o){return o.value===saved.region;})){region.value=saved.region;region.dispatchEvent(new Event('change',{bubbles:true}));if(Array.from(city.options).some(function(o){return o.value===saved.city;})){city.value=saved.city;city.dispatchEvent(new Event('change',{bubbles:true}));}}}catch(e){}finally{restoring=false;}}
    var selected=city.value!=='ALL'&&city.value?Array.from(city.options).find(function(o){return o.value===city.value;}):region.value!=='ALL'?Array.from(region.options).find(function(o){return o.value===region.value;}):null;
    var label=selected?selected.textContent+' · '+(uz?'O‘zgartirish':'Изменить'):uz?'Hududni tanlash':'Выбрать город';if(summary.textContent!==label)summary.textContent=label;
    chips.querySelectorAll('button').forEach(function(b){b.setAttribute('aria-pressed',String(b.dataset.category===category.value));});
  }
  document.addEventListener('change',function(e){if(e.target===region||e.target===city){if(!restoring){restored=true;try{localStorage.setItem(key,JSON.stringify({region:region.value,city:city.value}));}catch(e){}}if(e.target===city)place.open=false;}if([region,city,category].includes(e.target))sync();});
  new MutationObserver(sync).observe(selects,{childList:true,subtree:true});sync();
  function moveAds(){document.querySelectorAll('body>.relyqo-ad-top').forEach(function(ad){document.querySelector('main').append(ad);});}new MutationObserver(moveAds).observe(document.body,{childList:true});moveAds();
  var controller=new AbortController(),timer=setTimeout(function(){controller.abort();},8000);
  fetch('/v1/public/app-content',{signal:controller.signal,cache:'no-store'}).then(function(r){if(!r.ok)throw Error();return r.json();}).then(function(data){var copy=data.content&&data.content[uz?'uz':'ru'];if(!copy)return;if(typeof copy.title==='string')title.textContent=copy.title;if(typeof copy.hint==='string')hint.textContent=copy.hint;}).catch(function(){}).finally(function(){clearTimeout(timer);});
})();
`;
