export const strings = {
  ru: {
    country: 'Узбекистан', search: 'Найти', qr: 'Оценить', top: 'Рейтинги', account: 'Профиль',
    back: 'Назад', settings: 'Меню приложения', close: 'Закрыть', loading: 'Открываем RELYQO…',
    slow: 'Сервер просыпается. Первый запуск может занять около минуты.',
    failed: 'Не удалось подключиться', offline: 'Проверьте интернет и попробуйте ещё раз. Ваш аккаунт сохранён.',
    retry: 'Повторить', browser: 'Открыть в браузере', scanTitle: 'Оцените посещение',
    scanHint: 'Наведите камеру на одноразовый QR RELYQO с чека.',
    cameraHint: 'Камера нужна только для QR-кода. Видео не записывается.',
    allowCamera: 'Разрешить камеру', openSettings: 'Открыть настройки',
    denied: 'Доступ к камере выключен. Разрешите его в настройках или вставьте код ниже.',
    cameraFailed: 'Камера недоступна. Вставьте код с чека ниже.',
    browse: 'Нет QR? Найти организацию', manual: 'Вставить код вручную', code: 'Код из QR', verify: 'Подтвердить посещение',
    invalidQr: 'Это не QR посещения RELYQO. Отсканируйте код с чека организации.',
    scanned: 'QR распознан. Открываем оценку…', torch: 'Фонарик',
    privacy: 'Конфиденциальность', terms: 'Условия',
    about: 'Мобильное приложение для поиска услуг и честных оценок в Узбекистане.',
    preview: 'Тестовая версия · 1.1.0', external: 'Открыть внешнюю ссылку?',
    open: 'Открыть', cancel: 'Отмена', linkFailed: 'Не удалось открыть ссылку.',
    language: 'Переключить язык на узбекский', refresh: 'Обновить страницу',
  },
  uz: {
    country: 'O‘zbekiston', search: 'Qidiruv', qr: 'Baholash', top: 'Reytinglar', account: 'Profil',
    back: 'Orqaga', settings: 'Ilova menyusi', close: 'Yopish', loading: 'RELYQO ochilmoqda…',
    slow: 'Server ishga tushmoqda. Birinchi ochilish bir daqiqacha vaqt olishi mumkin.',
    failed: 'Ulanib bo‘lmadi', offline: 'Internetni tekshiring va qayta urinib ko‘ring. Hisobingiz saqlangan.',
    retry: 'Qayta urinish', browser: 'Brauzerda ochish', scanTitle: 'Tashrifni baholang',
    scanHint: 'Kamerani chekdagi bir martalik RELYQO QR-kodiga qarating.',
    cameraHint: 'Kamera faqat QR-kod uchun kerak. Video yozib olinmaydi.',
    allowCamera: 'Kameraga ruxsat berish', openSettings: 'Sozlamalarni ochish',
    denied: 'Kameraga ruxsat yo‘q. Sozlamalarda ruxsat bering yoki kodni quyiga kiriting.',
    cameraFailed: 'Kamera mavjud emas. Chekdagi kodni quyiga kiriting.',
    browse: 'QR yo‘qmi? Tashkilotni topish', manual: 'Kodni qo‘lda kiritish', code: 'QR-kod', verify: 'Tashrifni tasdiqlash',
    invalidQr: 'Bu RELYQO tashrif kodi emas. Tashkilot chekidagi kodni skanerlang.',
    scanned: 'QR aniqlandi. Baho sahifasi ochilmoqda…', torch: 'Chiroq',
    privacy: 'Maxfiylik', terms: 'Shartlar',
    about: 'O‘zbekistonda xizmatlarni topish va halol baholash uchun mobil ilova.',
    preview: 'Sinov versiyasi · 1.1.0', external: 'Tashqi havola ochilsinmi?',
    open: 'Ochish', cancel: 'Bekor qilish', linkFailed: 'Havolani ochib bo‘lmadi.',
    language: 'Tilni rus tiliga almashtirish', refresh: 'Sahifani yangilash',
  },
} as const;
export type Copy = typeof strings.ru | typeof strings.uz;
